config/routes.rb
Rails.application.routes.draw do

  # Scoring system
  get 'scores/index'
  get 'scores/create', to: 'scores#create'

  root 'home_page#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :teams
  post 'teams/add_to_team'
  delete 'teams/kick/:id', to: 'teams#kick', as: :teams_kick
  resources :posts

  resources :scores
  get 'news', to: 'pages#news'
  get 'team', to: 'pages#team'
  get 'tasks', to: 'pages#tasks'
  get 'account', to: 'pages#account'
  get 'admin/control_panel'
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @teams = Team.all
    @select_options = @teams.map { |t| t.name }.zip(@teams.map { |t| t.id })
  end

  def create
    if params[:stage] == '1'
      scores = params.permit(:analysis, :applicability, :innovativeness, :users_id, :teams_id)
      record = SemiFinalScore.create!(scores)
    else
      scores = params.permit(:analysis, :applicability, :innovativeness, :presentation, :users_id, :teams_id)
      record = FinalScore.create!(scores)
    end
    redirect_to scores_index_path
  end
end

app/helpers/scores_helper.rb
module ScoresHelper
  def calculate_sf_score(id)
    if SemiFinalScore.find_by(teams_id: id)
      team_sf_scores = SemiFinalScore.where(teams_id: id)
      (team_sf_scores.average(:analysis) + team_sf_scores.average(:innovativeness) + team_sf_scores.average(:applicability)).round(1)
    else
      0
    end
  end

  def calculate_f_score(id)
    if FinalScore.find_by(teams_id: id)
      team_sf_scores = FinalScore.where(teams_id: id)
      (team_sf_scores.average(:analysis) + team_sf_scores.average(:innovativeness) + team_sf_scores.average(:applicability) + team_sf_scores.average(:presentation)).round(1)
    else
      0
    end
  end
end

app/views/scores/_evaluation_form.html.erb
<div class="container bg-white rounded p-2 text-dark h-100">
  <h3 class="h3">Оценка</h3>
  <%= form_for(:final_scores, url: scores_create_final_path, method: :get) do |f| %>

    <%= f.hidden_field :teams_id, value: 15 %>
    <%= f.hidden_field :users_id, value: current_user.id %>
    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :analysis, 'Анализ:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :analysis, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :applicability, 'Применимость:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :applicability, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :innovativeness, 'Инновационность:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :innovativeness, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :presentation, 'Презентация:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :presentation, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2">
      <%= f.submit 'Оценить', class: 'btn btn-auth-proceed' %>
    </div>
  <% end %>
</div>

app/views/scores/_f_evaluation_form.html.erb
<div class="container bg-white rounded p-2 text-dark h-100">
  <h3 class="h3">Оценка</h3>
  <%= form_for(:final_scores, url: scores_create_final_path, method: :get) do |f| %>

    <%= f.hidden_field :teams_id, value: 15 %>
    <%= f.hidden_field :users_id, value: current_user.id %>
    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :analysis, 'Анализ:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :analysis, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :applicability, 'Применимость:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :applicability, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :innovativeness, 'Инновационность:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :innovativeness, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :presentation, 'Презентация:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :presentation, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2">
      <%= f.submit 'Оценить', class: 'btn btn-auth-proceed' %>
    </div>
  <% end %>
</div>

app/views/scores/_sf_evaluation_form.html.erb
<div class="container bg-white rounded p-2 text-dark h-100">
  <h3 class="h3">Оценка</h3>
  <%= form_for(:semi_final_scores, url: scores_create_semi_path, method: :get) do |f| %>

    <%= f.hidden_field :teams_id, value: 15 %>
    <%= f.hidden_field :users_id, value: current_user.id %>
    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :analysis, 'Анализ:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :analysis, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :applicability, 'Применимость:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :applicability, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2 row">
      <div class="col-3"><%= f.label :innovativeness, 'Инновационность:', class: 'form-label' %></div>
      <div class="col-9"><%= f.number_field :innovativeness, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
    </div>

    <div class="field text-start my-2">
      <%= f.submit 'Оценить', class: 'btn btn-auth-proceed' %>
    </div>
  <% end %>
</div>

app/views/scores/create_final.html.erb
<h1>Scores#create_final</h1>
<p>Find me in app/views/scores/create_final.html.erb</p>

app/views/scores/create_semi.html.erb
<h1>Scores#create_semi</h1>
<p>Find me in app/views/scores/create_semi.html.erb</p>

app/views/scores/index.html.erb
<%= render partial: 'layouts/navbar_home' %>
<% provide(:title, 'Оценки') %>

<div class="background-bubble bb-2"></div>
<div class="background-bubble bb-1"></div>
<div class="news-container container blurred-background purple-background mx-auto text-white w-100 p-3 h-100">
  <%= form_with(url: scores_create_path, method: :get, data: { turbo: false }) do |f| %>
  <div class="container d-flex my-2">
    <div class="w-75 me-3 h-100">
      <div class="container p-2">
        <h3 class="h3">Выбор команды</h3>
          <div class="field text-start my-2">
            <%= f.label :teams_id, 'Название команды', class: 'form-label' %><br/>
            <%= f.select :teams_id, options_for_select(@select_options), { include_blank: true }, class: 'form-select', required: :required %>
          </div>

          <div class="field text-start my-2">
            <%= f.label :stage, 'Этап', class: 'form-label' %><br/>
            <%= f.select :stage, options_for_select([['Отборочный', 1], ['Финальный', 2]]), { include_blank: true }, class: 'form-select', required: :required %>
          </div>
      </div>
    </div>
    <div class="w-100 ms-2">
      <div class="container bg-white rounded p-2 text-dark h-100">
        <h3 class="h3">Оценка</h3>

          <%= f.hidden_field :users_id, value: current_user.id %>
          <div class="field text-start my-2 row">
            <div class="col-3"><%= f.label :analysis, 'Анализ:', class: 'form-label' %></div>
            <div class="col-9"><%= f.number_field :analysis, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
          </div>

          <div class="field text-start my-2 row">
            <div class="col-3"><%= f.label :applicability, 'Применимость:', class: 'form-label' %></div>
            <div class="col-9"><%= f.number_field :applicability, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
          </div>

          <div class="field text-start my-2 row">
            <div class="col-3"><%= f.label :innovativeness, 'Инновационность:', class: 'form-label' %></div>
            <div class="col-9"><%= f.number_field :innovativeness, min: 1, max: 5, pattern: '\d*', class: 'form-control', required: :required %></div>
          </div>

          <%= f.hidden_field :presentation, value: 5 %>

          <div class="field text-start my-2">
            <%= f.submit 'Оценить', class: 'btn btn-auth-proceed' %>
          </div>
      </div>
    </div>
  </div>
  <% end %>
  <hr />
  <h3 class="h2 mt-3">Итоговая таблица</h3>
  <div class="container bg-white rounded my-3">
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Команда</th>
        <th>Отборотный этап</th>
        <th>Финальный этап</th>
      </tr>
      <% @teams.each do |t| %>
        <tr>
          <td><%= t.id %></td>
          <td><%= t.name %></td>
          <td><%= calculate_sf_score(t.id) %></td>
          <td><%= calculate_f_score(t.id) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/scores/new_final.html.erb
<h1>Scores#new_final</h1>
<p>Find me in app/views/scores/new_final.html.erb</p>

app/views/scores/new_semi.html.erb
<h1>Scores#new_semi</h1>
<p>Find me in app/views/scores/new_semi.html.erb</p>

app/views/scores/update_final.html.erb
<h1>Scores#update_final</h1>
<p>Find me in app/views/scores/update_final.html.erb</p>

app/views/scores/update_semi.html.erb
<h1>Scores#update_semi</h1>
<p>Find me in app/views/scores/update_semi.html.erb</p>