config/routes.rb
Rails.application.routes.draw do

  # Scoring system
  get 'scores/index'
  get 'scores/create', to: 'scores#create'

  root 'home_page#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :teams
  post 'teams/add_to_team'
  delete 'teams/kick/:id', to: 'teams#kick', as: :teams_kick
  resources :posts

  resources :scores
  get 'news', to: 'pages#news'
  get 'team', to: 'pages#team'
  get 'tasks', to: 'pages#tasks'
  get 'account', to: 'pages#account'
  get 'admin/control_panel'
end

app/models/post.rb
class Post < ApplicationRecord
  # belongs_to :user
  validates :header, presence: true
  validates :content, presence: true
  validates :author, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize, except: [:index]

  def authorize
    render file: 'public/422.html', layout: false, status: :unauthorized unless %w[admin moderator].include? current_user.role
  end

  def create
    post_params = params.require(:post).permit(:postHeader, :postContent)
    Post.create!(header: post_params[:postHeader], content: post_params[:postContent], author: current_user.id)
    redirect_back(fallback_location: new_post_path)
  end

  def destroy
    Post.destroy(params[:id])
    redirect_back(fallback_location: new_post_path)
  end

  def new
    @posts = Post.all
  end

  def index
    @posts = Post.all
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/index.html.erb
<%= render partial: 'layouts/navbar_home' %>
<% provide(:title, 'Новости') %>
<div class="background-bubble bb-2"></div>
<div class="background-bubble bb-1"></div>
<div class="news-container container blurred-background purple-background ms-3 me-auto text-white w-75 p-3">
  <h1 class="h1 fw-bold text-white text-white index">Новости хакатона</h1>
  <% if @posts.empty? %>
    <div class="container bg-white my-3 p-2 text-purple rounded shadow">
      <h2 class="h2 my-2">Пока нет новостей</h2>
    </div>
  <% end %>
  <% @posts.sort_by(&:created_at).reverse.each do |p| %>
    <div class="container bg-white my-3 p-2 text-purple rounded shadow">
      <h2 class="h2 my-2"><%= p.header %></h2>
      <p class="post-date"><%= p.created_at %></p>
      <%== p.content %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render partial: 'layouts/navbar_home' %>
<% provide(:title, 'Управление публицкациями') %>
<div class="background-bubble bb-2"></div>
<div class="background-bubble bb-1"></div>
<div class="news-container container blurred-background purple-background ms-3 me-auto text-white w-75 p-3">
  <h1 class="h1 fw-bold text-white text-white index">Новая публикация</h1>
  <div class="container bg-white my-3 p-2 text-purple rounded shadow">
    <%= form_for(:post, url: posts_path, data: { turbo: false }) do |f| %>
      <div class="field text-start my-2">
        <%= f.label :postHeader, 'Заголовок', class: 'form-label text-purple' %><br />
        <%= f.text_field :postHeader, autofocus: true, class: 'form-control' %>
      </div>
      <div class="field text-start my-2">
        <%= f.label :postHeader, 'Текст поста', class: 'form-label text-purple' %><br />
        <p class="form-text">Помните, что при написании текста поста рекомендуется использовать оформление с помоющью тегов HTML</p>
        <%= f.text_area :postContent, class: 'form-control', rows: 3 %>
      </div>
      <div class="field text-start my-2">
        <%= f.submit 'Опубликовать', class: 'btn btn-auth-proceed' %><br />
      </div>
    <% end %>
  </div>
  <hr class="text-white" />
  <h1 class="h1 fw-bold text-white text-white index">Все посты</h1>
  <div class="container bg-white my-3 p-2 text-purple rounded shadow">
    <% if @posts.empty? %>
      <h2 class="h2 my-2">Пока нет публикаций</h2>
    <% else %>
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Заголовок</th>
          <th>Автор</th>
          <th>Время создания</th>
          <th></th>
        </tr>
        <% Post.all.sort_by(&:id).each do |p| %>
          <tr>
            <td><%= p.id %></td>
            <td><%= p.header %></td>
            <td><%= p.author %></td>
            <td><%= p.created_at %></td>
            <td><%= button_to 'Удалить', post_path(p.id), method: :delete, data: { turbo: false, confirm: "Вы уверены?" }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>