config/routes.rb
Rails.application.routes.draw do

  # Scoring system
  get 'scores/index'
  get 'scores/create', to: 'scores#create'

  root 'home_page#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :teams
  post 'teams/add_to_team'
  delete 'teams/kick/:id', to: 'teams#kick', as: :teams_kick
  resources :posts

  resources :scores
  get 'news', to: 'pages#news'
  get 'team', to: 'pages#team'
  get 'tasks', to: 'pages#tasks'
  get 'account', to: 'pages#account'
  get 'admin/control_panel'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/final_score.rb
class FinalScore < ApplicationRecord
  validate :jury_is_actually_jury
  # belongs_to :team
  # belongs_to :user

  private
  def jury_is_actually_jury
    unless User.find(users_id).role == 'jury'
      errors.add(:users_id, 'В поле users_id должен быть участник с ролью 2 (jury)')
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # belongs_to :user
  validates :header, presence: true
  validates :content, presence: true
  validates :author, presence: true
end

app/models/semi_final_score.rb
class SemiFinalScore < ApplicationRecord
  validate :jury_is_actually_jury
  # belongs_to :team
  # belongs_to :user

  private
  def jury_is_actually_jury
    unless User.find(users_id).role == 'jury'
      errors.add(:users_id, 'В поле users_id должен быть участник с ролью 2 (jury)')
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  enum track: [:web_development, :data_science, :java_backend]
  validates :name, presence: true
  validates :track, presence: true
  validates_uniqueness_of :name, :leader
  has_many :user
  has_many :semi_final_score, dependent: :destroy
  has_many :final_score, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :jury, :admin]
  after_initialize :set_default_role, if: :new_record?
  belongs_to :team, optional: true
  has_many :semi_final_score
  has_many :final_score

  # has_many :posts
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize

  def authorize
    render file: 'public/422.html', layout: false, status: :unauthorized unless current_user.role == 'admin'
  end

  def control_panel
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def news
  end

  def team
  end

  def tasks
  end

  def account
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize, except: [:index]

  def authorize
    render file: 'public/422.html', layout: false, status: :unauthorized unless %w[admin moderator].include? current_user.role
  end

  def create
    post_params = params.require(:post).permit(:postHeader, :postContent)
    Post.create!(header: post_params[:postHeader], content: post_params[:postContent], author: current_user.id)
    redirect_back(fallback_location: new_post_path)
  end

  def destroy
    Post.destroy(params[:id])
    redirect_back(fallback_location: new_post_path)
  end

  def new
    @posts = Post.all
  end

  def index
    @posts = Post.all
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @teams = Team.all
    @select_options = @teams.map { |t| t.name }.zip(@teams.map { |t| t.id })
  end

  def create
    if params[:stage] == '1'
      scores = params.permit(:analysis, :applicability, :innovativeness, :users_id, :teams_id)
      record = SemiFinalScore.create!(scores)
    else
      scores = params.permit(:analysis, :applicability, :innovativeness, :presentation, :users_id, :teams_id)
      record = FinalScore.create!(scores)
    end
    redirect_to scores_index_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize, only: [:index]

  def authorize
    render file: 'public/422.html', layout: false, status: :unauthorized unless current_user.role == 'admin'
  end

  def index
    @users_with_no_team = User.where(teams_id: nil)
    @teams = Team.all.map do |t|
      leader = t.leader.nil? ? nil : User.find(t.leader)
      if leader.nil?
        members = User.where(teams_id: t.id)
      else
        members = User.where(teams_id: t.id).where.not(id: leader.id).to_a
      end
      {data: t, leader: leader, members: members }
    end
  end

  def add_to_team
    user_params = params.require(:teams).permit(:id)
    members = User.where(teams_id: user_params[:id])
    if members.length >= 4 or not Team.exists?(user_params[:id].to_i)
      redirect_to new_team_path
    else
      logger.debug(Team.exists?(user_params[:id].to_i))
      current_user.update!(teams_id: user_params[:id])
      redirect_to team_path(current_user.teams_id)
    end
  end

  def kick
    user_id = params[:id].to_i
    if user_id == current_user.id
      team = Team.find(current_user.teams_id)
      if team.leader == current_user.id
        team.update!(leader: nil)
      end
      current_user.update(teams_id: nil)


      redirect_to new_team_path
    else
      redirect_back(fallback_location: team_path(current_user.id))
    end
  end

  def destroy
    User.where(teams_id: params[:id]).update!(teams_id: nil)
    Team.destroy(params[:id].to_i)
    redirect_to new_team_path
  end

  def create
    begin
      team_params = params.require(:teams).permit(:name, :track)
      new_team = Team.create!(name: team_params[:name], track: team_params[:track].to_i, leader: current_user.id)
      current_user.update!(teams_id: new_team.id)
      redirect_to team_path(new_team.id)
    rescue ActiveRecord::RecordInvalid => err
      redirect_to new_team_path
    end
  end

  def show
    @team = Team.find(params[:id].to_i)
    @leader = User.find(@team.leader)
    @members = User.where(teams_id: @team.id).where.not(id: @leader.id)
  end

  def edit
  end

  def new
    if current_user.first_name.nil? or current_user.last_name.nil? or current_user.first_name.empty? or current_user.last_name.empty?
      redirect_to edit_user_registration_path
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
  def full_page_title(title='')
    if title.empty?
      'BEAST Hack | Соревнование для студентов'
    else
      "#{title} | BEAST Hack"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
  def calculate_sf_score(id)
    if SemiFinalScore.find_by(teams_id: id)
      team_sf_scores = SemiFinalScore.where(teams_id: id)
      (team_sf_scores.average(:analysis) + team_sf_scores.average(:innovativeness) + team_sf_scores.average(:applicability)).round(1)
    else
      0
    end
  end

  def calculate_f_score(id)
    if FinalScore.find_by(teams_id: id)
      team_sf_scores = FinalScore.where(teams_id: id)
      (team_sf_scores.average(:analysis) + team_sf_scores.average(:innovativeness) + team_sf_scores.average(:applicability) + team_sf_scores.average(:presentation)).round(1)
    else
      0
    end
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
  def show_or_new(user)
    if user.teams_id
      team_path(user.teams_id)
    else
      new_team_path
    end
  end
end

app/views/admin/control_panel.html.erb
<%= render partial: 'layouts/navbar_home' %>
<% provide(:title, 'Панель управления') %>
<h1>Admin#control_panel</h1>
<p>Find me in app/views/admin/control_panel.html.erb</p>

app/views/layouts/_navbar_home.html.erb
<div class="navbar navbar-expand-md shadow fixed-top px-2">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "BEAST Hack", root_path('#'), class: 'navbar-brand text-white fw-bold' %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
      <div class="navbar-nav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "Новости", posts_path, class: 'nav-link text-white' %></li>
          <% unless ['admin', 'moderator'].include? current_user.role %>
<!--            <li class="nav-item"><%#= link_to "Задания", tasks_path, class: 'nav-link text-white' %></li>-->
            <li class="nav-item"><%= link_to "Команда", show_or_new(current_user), class: 'nav-link text-white' %></li>
          <% end %>
          <li class="nav-item"><%= link_to "Личный кабинет", edit_user_registration_path, class: 'nav-link text-white' %></li>
            <% if ['admin', 'jury'].include? current_user.role %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Управление
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Команды", teams_path, class: 'nav-link text-purple dropdown-item' %></li>
                  <li><%= link_to "Оценки", scores_index_path, class: 'nav-link text-purple dropdown-item' %></li>
                  <% if current_user.role == 'admin' %>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Редактор публикаций", new_post_path, class: 'nav-link text-purple dropdown-item' %></li>
                  <% end %>
                </ul>
              </li>
            <% end %>
        <% else %>
          <li class="nav-item"><%= link_to "О нас", root_path+'#indexAbout', class: 'nav-link text-white' %></li>
          <li class="nav-item"><%= link_to "Партнерам", root_path+'#indexPartners', class: 'nav-link text-white' %></li>
        <% end %>
        </ul>
      </div>
      <div class="d-flex nav navbar-nav navbar-right w">
        <% if user_signed_in? %>
          <%= button_to "Выйти", destroy_user_session_path, method: :delete,
                        data: { turbo: false }, class: 'btn btn-outline-light btn-nav mx-1' %>
        <% else %>
          <%= button_to "Вход", new_user_session_path, method: :get,
                        data: { turbo: false }, class: 'btn btn-outline-light btn-nav mx-1' %>
          <%= button_to "Регистрация", new_user_registration_path, method: :get,
                        data: { turbo: false }, class: 'btn btn-outline-light btn-nav mx-1' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div style="height: 70px"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= full_page_title(yield(:title)) %></title>
    <%= favicon_link_tag asset_path('beast_hack_favicon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= yield(:page) %>">

  <% if alert %>
    <div class="container col-md-6 fixed-top my-3 text-center" style="z-index: 1050">
      <div class="alert alert-warning alert-dismissible fade show purple-background border border-0 text-white" role="alert">
        <%= alert %>
        <button type="button" class="btn-close text-purple" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
  <% end %>

  <% if notice %>
    <div class="container col-md-9 fixed-top my-3 text-center" style="z-index: 1050">
      <div class="alert alert-warning alert-dismissible fade show purple-background border border-0 text-white" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
  <% end %>

    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</html>

app/views/pages/account.html.erb
<%= render partial: 'layouts/navbar_home' %>
<% provide(:title, 'Личный кабинет') %>
<div class="background-bubble bb-1"></div>
<div class="background-bubble bb-2"></div>
<div class="container text-center mx-4">
  <div class="col-md-5 text-center mx-auto my-5 border rounded p-5 auth-window">
    <h2 class="h1 text-white mb-5">Регистрация</h2>

    <%= form_for(:user, url: edit_user_path, data: { turbo: false }) do |f| %>
      <%= render "devise/shared/error_messages", resource: resource %>

      <div class="field text-start my-2">
        <%= f.label :first_name, 'Имя', class: 'form-label text-white' %><br />
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="field text-start my-2">
        <%= f.label :first_name, 'Имя', class: 'form-label text-white' %><br />
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="field text-start my-2">
        <%= f.label :email, 'Email', class: 'form-label text-white' %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', readonly: :readonly %>
      </div>

      <div class="field text-start my-2">
        <%= f.label :password, 'Пароль', class: 'form-label text-white' %>
        <% if @minimum_password_length %>
          <em class="form-text text-light">(Минимум <%= @minimum_password_length %> символов)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
      </div>

      <div class="field text-start my-2">
        <%= f.label :password_confirmation, 'Подтверждение пароля', class: 'form-label text-white' %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
      </div>

      <!--      <div class="actions my-4 d-flex">-->
      <!--        <div class="w-50 px-1"><%#= button_to 'Назад', :back, class: 'btn btn-auth-back w-100' %></div>-->
      <div class="w-50 px-1"><%= f.submit "Зарегистрироваться", class: 'btn btn-auth-proceed w-100' %></div>
      <!--      </div>-->
    <% end %>

    <%= render "devise/shared/links" %>

  </div>
</div>

app/views/pages/tasks.html.erb
<%= render partial: 'layouts/navbar_home' %>
<% provide(:title, 'Задания') %>
<h1>Pages#tasks</h1>
<p>Find me in app/views/pages/tasks.html.erb</p>